### ISSUE TITLE
Module Create Error

### ISSUE THREAD

**Issue by d3ancole1995** [death-droid/Pterodactyl-WHMCS#7]
I've setup the panel. Configured the daemon. Everything is up.

I've installed the plugin. Added the server (clicked the test button and got success message)
I've added "Minecraft" product as installation pictures indicate.

I've created order for the product. Accepted it. When I click "Create" under "Module Commands" I get error at top of the page.

![image](https://user-images.githubusercontent.com/5874689/27254901-43f43972-538a-11e7-915c-93bb2727b4b5.png)

I have enabled module debug logging. Error response below for "Action" - /api/admin/servers?include=allocations:

```
Array
(
    [error] => An unhandled exception occured while attemping to add this server. Please try again.
    [status_code] => 500
)
```

I have checked the logs on the panel. and have also included below.

```
[2017-06-17 17:26:49] production.ERROR: InvalidArgumentException: You requested 1 items, but there are only 0 items in the collection. in /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Support/Collection.php:988
Stack trace:
#0 /var/www/sites/panel.dynodigital.net/app/Services/DeploymentService.php(253): Illuminate\Support\Collection->random()
#1 /var/www/sites/panel.dynodigital.net/app/Repositories/ServerRepository.php(144): Pterodactyl\Services\DeploymentService->select()
#2 /var/www/sites/panel.dynodigital.net/app/Http/Controllers/API/Admin/ServerController.php(99): Pterodactyl\Repositories\ServerRepository->create(Array)
#3 [internal function]: Pterodactyl\Http\Controllers\API\Admin\ServerController->store(Object(Illuminate\Http\Request))
#4 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#5 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('store', Array)
#6 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Pterodactyl\Http\Controllers\API\Admin\ServerController), 'store')
#7 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#8 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(559): Illuminate\Routing\Route->run()
#9 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), '60', '1')
#15 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /var/www/sites/panel.dynodigital.net/app/Http/Middleware/HMACAuthorization.php(98): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Pterodactyl\Http\Middleware\HMACAuthorization->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(561): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(520): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#22 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(498): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#23 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(174): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#24 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/sites/panel.dynodigital.net/vendor/fideloper/proxy/src/TrustProxies.php(55): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 /var/www/sites/panel.dynodigital.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#43 /var/www/sites/panel.dynodigital.net/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#44 {main}
```

If you need more information let me know and I will provide what ever you need.

**Comment by d3ancole1995** [comment]
I'd forgotten to setup allocations.

My fault. But there was no indication of this so at least I pointed it out.
